import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from 'react-native-responsive-screen';

export const estilo = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: hp('5%'),
    paddingHorizontal: wp('4%'),
  },
  titulo: {
    fontSize: hp('3.5%'),
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: hp('1.5%'),
  },
  subtitulo: {
    fontSize: hp('2%'),
    textAlign: 'center',
    marginBottom: hp('3.5%'),
    fontStyle: 'italic',
    paddingHorizontal: wp('3%'),
    lineHeight: hp('2.8%'),
  },
  secao: {
    fontSize: hp('2.2%'),
    marginBottom: hp('1.5%'),
    fontWeight: '600',
  },
  categoriasContainer: {
    flexDirection: 'row',
    marginBottom: hp('2.5%'),
    paddingVertical: hp('1%'),
  },
  categoriaBotao: {
    paddingVertical: hp('1.2%'),
    paddingHorizontal: wp('4.5%'),
    borderRadius: hp('2.8%'),
    marginRight: wp('2.5%'),
    borderWidth: 1,
  },
  categoriaTexto: {
    fontSize: hp('1.8%'),
    fontWeight: '500',
  },
  card: {
    marginRight: wp('4%'),
    alignItems: 'center',
    width: wp('35%'),
    padding: wp('2.5%'),
    borderRadius: hp('1.2%'),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: hp('0.4%') },
    shadowOpacity: 0.4,
    shadowRadius: hp('0.6%'),
    elevation: 6,
  },
  capa: {
    width: wp('28%'),
    height: hp('20%'),
    resizeMode: 'cover',
    borderRadius: hp('0.8%'),
  },
  texto: {
    textAlign: 'center',
    fontSize: hp('1.6%'),
    marginTop: hp('1%'),
    fontWeight: '500',
  },
  botao: {
    marginTop: hp('5%'),
    marginBottom: hp('7.5%'),
    paddingVertical: hp('2%'),
    paddingHorizontal: wp('8%'),
    borderRadius: hp('1.8%'),
    borderWidth: 1.5,
    alignItems: 'center',
    shadowOffset: { width: 0, height: hp('0.3%') },
    shadowOpacity: 0.5,
    shadowRadius: hp('0.6%'),
    elevation: 6,
  },
  botaoTexto: {
    fontSize: hp('2%'),
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  temaContainer: {
    alignItems: 'flex-end',
  },
  temaBotao: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginBottom: hp('1.5%'),
    paddingHorizontal: wp('4%'),
    paddingVertical: hp('1.2%'),
    borderRadius: hp('2.5%'),
  },
  temaTexto: {
    marginRight: wp('2%'),
  },
  dropdown: {
    position: 'absolute',
    top: hp('5.5%'),
    right: 0,
    borderWidth: 1,
    borderRadius: hp('1.2%'),
    paddingVertical: hp('1%'),
    width: wp('60%'),
    zIndex: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: hp('0.3%') },
    shadowOpacity: 0.25,
    shadowRadius: hp('0.5%'),
  },
  dropdownItem: {
    paddingVertical: hp('1.2%'),
    width: '100%',
    alignItems: 'center',
  },
  capaContainer: {
    width: wp('28%'),
    height: hp('20%'),
    borderRadius: hp('0.8%'),
    overflow: 'hidden',
    marginBottom: hp('1%'),
  },
  header: {
    alignItems: 'center',
    marginBottom: hp('2.5%'),
  },
  avatar: {
    width: wp('24%'),
    height: wp('24%'),
    borderRadius: wp('12%'),
    borderWidth: 2,
    marginBottom: hp('1.5%'),
  },
  semCapa: {
    width: wp('14%'),
    height: hp('10%'),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: hp('1%'),
    marginBottom: hp('1%'),
  },
  video: {
    width: wp('32%'),
    height: hp('28%'),
    borderRadius: hp('1%'),
  },
});
