import { StyleSheet } from 'react-native';

export const estilo = StyleSheet.create({
  container: {
    flex: 1,
    paddingTop: 50,
    paddingHorizontal: 16,
  },
  titulo: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitulo: {
    fontSize: 15,
    textAlign: 'center',
    marginBottom: 30,
    fontStyle: 'italic',
    paddingHorizontal: 10,
    lineHeight: 22,
  },
  secao: {
    fontSize: 18,
    marginBottom: 12,
    fontWeight: '600',
  },
  categoriasContainer: {
    flexDirection: 'row',
    marginBottom: 20,
    paddingVertical: 5,
  },
  categoriaBotao: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 22,
    marginRight: 10,
    borderWidth: 1,
  },
  categoriaTexto: {
    fontSize: 14,
    fontWeight: '500',
  },
  card: {
    marginRight: 16,
    alignItems: 'center',
    width: 130,
    padding: 10,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 6,
  },
  capa: {
    width: 100,
    height: 150,
    resizeMode: 'cover',
    borderRadius: 6,
  },
  texto: {
    textAlign: 'center',
    fontSize: 13,
    marginTop: 8,
    fontWeight: '500',
  },
  botao: {
    marginTop: 40,
    marginBottom: 60,
    paddingVertical: 16,
    paddingHorizontal: 30,
    borderRadius: 14,
    borderWidth: 1.5,
    alignItems: 'center',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 6,
  },
  botaoTexto: {
    fontSize: 16,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  temaContainer: {
    alignItems: 'flex-end',
  },
  temaBotao: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    marginBottom: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  temaTexto: {
    marginRight: 8,
  },
  dropdown: {
    position: 'absolute',
    top: 46,
    right: 0,
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 8,
    width: 220,
    zIndex: 10,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
  },
  dropdownItem: {
    paddingVertical: 10,
    width: '100%',
    alignItems: 'center',
  },
  capaContainer: {
    width: 100,
    height: 150,
    borderRadius: 6,
    overflow: 'hidden',
    marginBottom: 8,
  },
  
  header: {
    alignItems: 'center',
    marginBottom: 19,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 100,
    borderWidth: 2,
    marginBottom: 10,
  },
  semCapa: {
    width: 54,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
    marginBottom: 8,
  },
  video: {
    width: 120,
    height: 225,
    borderRadius: 8,
  },
});
